#!/bin/bash
#SBATCH -n 4
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=2048
#SBATCH --time=2-00:00:00

python train.py \
    --input ../new-implementation/dataset \
    --gpu \
    --output output \
    --epochs 200 \
    --batch 2;
